# Based on
# - https://github.com/securego/gosec

name: go-security.yaml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      LD_LIBRARY_PATH: /opt/senzing/g2/lib/
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - run: wget -qO /tmp/senzingrepo_1.0.1-1_amd64.deb https://senzing-production-apt.s3.amazonaws.com/senzingrepo_1.0.1-1_amd64.deb
      - run: sudo apt-get -y install /tmp/senzingrepo_1.0.1-1_amd64.deb
      - run: sudo apt-get update
      - run: sudo --preserve-env apt-get -y install senzingapi
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: -exclude=G103 ./...
