name: Go test windows

on: [pull_request, workflow_dispatch]

env:
  SENZING_LOG_LEVEL: TRACE
  SENZING_TOOLS_DATABASE_URL: "sqlite3://na:na@nowhere/C:\\Temp\\sqlite\\G2C.db"

permissions:
  contents: read

jobs:
  go-test-windows:
    name: "Go test with Senzing: ${{ matrix.senzingapi-version }}; OS: ${{ matrix.os }}; Go: ${{ matrix.go }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.21"]
        os: [windows-latest]
        senzingapi-version: [staging-v4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Senzing API
        uses: senzing-factory/github-action-install-senzing-api@v3
        with:
          senzingapi-version: ${{ matrix.senzingapi-version }}

      - name: XXX install dependencies
        run: |
          choco install -y dependencies

      - name: XXX Run redist
        shell: pwsh
        run: |
          "C:\Program Files\senzing\er\redis\vc_redist.x64.exe /q /norestart"

      - name: XXX view dependencies
        shell: pwsh
        run: |
          $env:Path
          ls "C:\Program Files\senzing\er\lib\"

      - name: XXX view dependencies chain 2
        run: |
          dependencies.exe -chain "C:\Program Files\senzing\er\lib\Sz.dll" -depth 1

      - name: Add to "Path" environment variable
        run: |
          echo "$Env:PATH=$Env:PATH;C:\Program Files\senzing\er\lib" >> $env:GITHUB_PATH
          # printf "C:\Program Files\senzing\er\lib" | Out-File -FilePath "$env:GITHUB_PATH" -Encoding utf8 -Append

      - name: XXX Check path
        run: |
          $env:Path

      - name: Copy /etc files
        run: copy testdata/senzing-license/g2.lic "C:\Program Files\senzing\er\etc\g2.lic"

      - name: Copy test database files
        run: mkdir "C:\Temp\sqlite" && copy testdata/sqlite/G2C.db "C:\Temp\sqlite\G2C.db"

      - name: Run go test
        run: |
          # $env:Path += “;C:\Program Files\senzing\er\lib”
          $env:Path
          go test -json -v -p 1 -coverprofile=cover -covermode=atomic -coverpkg=./... ./... 2>&1 | tee "C:\Temp\gotest.log" | gotestfmt
          cp cover cover.out

      - name: Store coverage file
        uses: actions/upload-artifact@v4
        with:
          name: cover.out
          path: cover.out

      - name: Upload test log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-log
          path: "C:\\Temp\\gotest.log"
          if-no-files-found: error

  coverage:
    name: Coverage
    needs: go-test-windows
    uses: senzing-factory/build-resources/.github/workflows/go-coverage.yaml@v2
    with:
      coverage-config: ./.github/coverage/testcoverage.yaml
