# Based on
# - https://github.com/marketplace/actions/setup-go-environment

name: go-test-windows.yaml

on: [push]

env:
  LD_LIBRARY_PATH: /opt/senzing/g2/lib
  SENZING_TOOLS_DATABASE_URL: 'sqlite3://na:na@nowhere/C:\Temp\sqlite\G2C.db'

jobs:
  build:
    runs-on: windows-latest
    env:
      GO111MODULE: on
      CGO_ENABLED: 1
    strategy:
      matrix:
        go: ["1.21"]
    name: Go ${{ matrix.go }} - windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: DEBUG - List environment variables #1
        run: env
      - name: DEBUG - Update Path variable
        run: echo "C:\Program Files\Senzing\g2\lib>" >> $GITHUB_PATH
      - name: DEBUG - List environment variables #2
        run: env
      - name: Install Senzing API
        uses: Senzing/github-action-install-senzing-api@main
      - name: Copy /etc files
        run: copy testdata/senzing-license/g2.lic "C:\Program Files\Senzing\g2\etc\g2.lic"
      - name: Copy test database files
        run: mkdir "C:\Temp\sqlite" && copy testdata/sqlite/G2C.db "C:\Temp\sqlite\G2C.db"
      - name: DEBUG - List g2\lib
        run: dir "C:\Program Files\Senzing\g2\lib>"
      - name: Update Path variable
        run: echo "C:\Program Files\Senzing\g2\lib>" >> $GITHUB_PATH
      # - name: Run go test
      #   run: go test -v -p 1 ./...
      - name: Run go test - main
        run: go test -v -p 1 ./.
      - name: Run go test - g2config
        run: go test -v -p 1 ./g2config
      - name: Run go test - g2configmgr
        run: go test -v -p 1 ./g2configmgr
      - name: Run go test - g2product
        run: go test -v -p 1 ./g2product
