name: gosec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  LD_LIBRARY_PATH: /opt/senzing/g2/lib

permissions:
  contents: read

jobs:
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      CGO_ENABLED: 1

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Install Senzing API
        uses: senzing-factory/github-action-install-senzing-api@v3
        with:
          senzingapi-version: production-v3

      - run: |
          mkdir ./szconfig/gohelpers
          cp /opt/senzing/g2/sdk/c/*.h ./szconfig/
          cp /opt/senzing/g2/sdk/c/gohelpers/*.h ./szconfig/gohelpers
          mkdir ./szconfigmanager/gohelpers
          cp /opt/senzing/g2/sdk/c/*.h ./szconfigmanager/
          cp /opt/senzing/g2/sdk/c/gohelpers/*.h ./szconfigmanager/gohelpers
          mkdir ./szdiagnostic/gohelpers
          cp /opt/senzing/g2/sdk/c/*.h ./szdiagnostic/
          cp /opt/senzing/g2/sdk/c/gohelpers/*.h ./szdiagnostic/gohelpers
          mkdir ./szengine/gohelpers
          cp /opt/senzing/g2/sdk/c/*.h ./szengine/
          cp /opt/senzing/g2/sdk/c/gohelpers/*.h ./szengine/gohelpers
          mkdir ./szproduct/gohelpers
          cp /opt/senzing/g2/sdk/c/*.h ./szproduct/
          cp /opt/senzing/g2/sdk/c/gohelpers/*.h ./szproduct/gohelpers

      - name: run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: -exclude=G103 -verbose text ./...
